defmodule VoxWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :vox

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_vox_key",
    signing_salt: "U0TN+8oT",
    same_site: "Lax"
  ]

  # WebRTC signaling socket. check_origin is relaxed for local dev so the
  # Vite dev server (localhost:5173) can connect; tighten this for production.
  socket "/socket", VoxWeb.UserSocket,
    websocket: [check_origin: false],
    longpoll: false

  # Serve the bundled single-page app (assets + index.html) if present.
  plug Plug.Static,
    at: "/",
    from: {:vox, "priv/static/app"},
    gzip: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :vox,
    gzip: not code_reloading?,
    only: VoxWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Allow the web client (different origin in dev) to call the blob endpoints.
  plug CORSPlug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Media uploads (ciphertext) can be a few MB.
    length: 30_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug VoxWeb.Router
end
